"""widen_signals_coin_symbol_to_50

Revision ID: 21de8d06f2c5
Revises: 3b08a7aa2b1e
Create Date: 2026-03-28 00:49:57.807827

"""
from alembic import op
import sqlalchemy as sa


revision = '21de8d06f2c5'
down_revision = '3b08a7aa2b1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signals', 'coin_symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signals', 'coin_symbol',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
