"""widen_coin_symbol_to_50

Revision ID: 3b08a7aa2b1e
Revises: 003
Create Date: 2026-03-28 00:48:42.189528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3b08a7aa2b1e'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('coins', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('coins', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('coins', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dex_tokens', 'has_twitter',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dex_tokens', 'has_telegram',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dex_tokens', 'has_website',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dex_tokens', 'is_boosted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dex_tokens', 'pair_created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('dex_tokens', 'large_tx_detected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dex_tokens', 'sniping_opportunity',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dex_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dex_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_dex_tokens_snipe_score', table_name='dex_tokens')
    op.drop_index('ix_dex_tokens_sniping_opportunity', table_name='dex_tokens')
    op.alter_column('signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_dex_tokens_sniping_opportunity', 'dex_tokens', ['sniping_opportunity'], unique=False)
    op.create_index('ix_dex_tokens_snipe_score', 'dex_tokens', ['snipe_score'], unique=False)
    op.alter_column('dex_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dex_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dex_tokens', 'sniping_opportunity',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dex_tokens', 'large_tx_detected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dex_tokens', 'pair_created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('dex_tokens', 'is_boosted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dex_tokens', 'has_website',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dex_tokens', 'has_telegram',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dex_tokens', 'has_twitter',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('coins', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('coins', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('coins', 'symbol',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
