"""widen_alerts_coin_symbol_to_50

Revision ID: 43950320aec7
Revises: 21de8d06f2c5
Create Date: 2026-03-28 00:57:01.346297

"""
from alembic import op
import sqlalchemy as sa


revision = '43950320aec7'
down_revision = '21de8d06f2c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'coin_symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'coin_symbol',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
